modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="exastorage"
version="Alpha"
displayName="Exastorage Mod "
displayURL=""
logoFile=""
credits=""
authors="SixFourSeven for the ideas, Khorbos for making the mod and textures."
description='''
In the era of enormous data, a simple key can store your entire life'''

